<a href="https://colab.research.google.com/github/dernlosonotsolo/PythonDataViz2026/blob/main/Pandas101_dernlosonotsolo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

path = '/content/drive/My Drive/PythonDataViz2026' #path เส้นทางชี้ไปไฟล์

In [ ]:
covid_file_path = os.path.join(path,'confirmed-cases.csv')  # os.path.join ให้ path เชื่อมos กับ join
print(covid_file_path)

/content/drive/My Drive/PythonDataViz2026/confirmed-cases.csv

In [ ]:
a = path + '/confirmed-cases.csv'
print(a)

/content/drive/My Drive/PythonDataViz2026/confirmed-cases.csv

##load data to memory

In [ ]:
data_covid = pd.read_csv(covid_file_path)
data_covid

/tmp/ipykernel_662/318669438.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv(covid_file_path)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
...,...,...,...,...,...,...,...,...,...,...,...
839766,839767,12/8/2021,11/8/2021,ชาย,52.0,ปี,NaN,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839767,839768,12/8/2021,11/8/2021,ชาย,34.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839768,839769,12/8/2021,11/8/2021,ชาย,31.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839769,839770,12/8/2021,11/8/2021,ชาย,83.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839770,839771,12/8/2021,11/8/2021,ชาย,47.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN

In [ ]:
data_covid.head() #โชว์หัวตาราง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [ ]:
data_covid.shape #มีกี่แถวกี่หลัก

(839771, 11)

##ชี้ค่าในตางราง

In [ ]:
data_covid['province_of_onset']

0         กรุงเทพมหานคร
1         กรุงเทพมหานคร
2                นครปฐม
3         กรุงเทพมหานคร
4         กรุงเทพมหานคร
              ...
839766        กาญจนบุรี
839767        กาญจนบุรี
839768        กาญจนบุรี
839769        กาญจนบุรี
839770        กาญจนบุรี
Name: province_of_onset, Length: 839771, dtype: object

In [ ]:
data_covid['province_of_onset'][4]

'กรุงเทพมหานคร'

## .iloc

จะมองค่าเป็นตารางแทน

In [ ]:
data_covid.iloc[4,7]

'นนทบุรี'

## Table slicing

### ตัดมาเฉพาะ column ที่ต้องการ

In [ ]:
smaller_table = data_covid[['announce_date','province_of_onset','risk']]
smaller_table

       announce_date province_of_onset                              risk
0          12/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
1          17/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
2          22/1/2020            นครปฐม  คนต่างชาติเดินทางมาจากต่างประเทศ
3          22/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
4          24/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
...              ...               ...                               ...
839766     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ
839767     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ
839768     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ
839769     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ
839770     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ

[839771 rows x 3 columns]

#### ตัดเฉพาะ rows ที่ต้องการ

##### แบบง่าย แต่ใช้การอะไรไม่ค่อยจะได้ (มองเป็น array แล้วตัดแบบ array)

In [ ]:
data_covid.iloc[1:5,:]

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

แบบ advanced แต่ใช้ประโยชน์ได้เยอะกว่า (ตัดแบบใช้ logic query)

In [ ]:
data_covid[data_covid['province_of_onset']=='ขอนแก่น']

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
181,182,18/3/2020,15/3/2020,ชาย,33.0,ปี,Thailand,ขอนแก่น,สนามมวย,ขอนแก่น,เมือง
463,464,22/3/2020,21/3/2020,หญิง,36.0,ปี,Thailand,ขอนแก่น,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,เมือง
1467,1468,30/3/2020,26/3/2020,ชาย,19.0,ปี,Thailand,ขอนแก่น,คนไทยเดินทางกลับจากต่างประเทศ,ขอนแก่น,เมือง
1971,1972,3/4/2020,31/3/2020,หญิง,70.0,ปี,Thailand,ขอนแก่น,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ขอนแก่น,เมือง
2638,2639,15/4/2020,14/4/2020,หญิง,63.0,ปี,Thailand,ขอนแก่น,สัมผัสผู้เดินทางจากต่างประเทศ,ขอนแก่น,น้ำพอง
...,...,...,...,...,...,...,...,...,...,...,...
839669,839670,12/8/2021,11/8/2021,ชาย,46.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839670,839671,12/8/2021,11/8/2021,ชาย,58.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839671,839672,12/8/2021,11/8/2021,ชาย,30.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839672,839673,12/8/2021,11/8/2021,ชาย,20.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839673,839674,12/8/2021,11/8/2021,ชาย,20.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN

การชี้ค่าในตาราง data_covid[x] x สามารถมีค่าที่ใส่เข้าไปได้ 2 แบบ


1.   ชื่อ column
2.   ใส่ rows ที่ต้องการ(ใส่ list ที่มีขนาดเท่ากับจำนวนแถว แล้วบอกว่าเอาแถวไหนบ้างโดยใช้ logicla expression(True/False))

In [ ]:
eight_rows_covid = data_covid.iloc[:8,:] # ตารางตัวอย่าง
eight_rows_covid

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
5,6,25/1/2020,NaN,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
6,7,26/1/2020,NaN,หญิง,57.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
7,8,26/1/2020,NaN,หญิง,73.0,ปี,China,ประจวบคีรีขันธ์,คนต่างชาติเดินทางมาจากต่างประเทศ,ประจวบคีรีขันธ์,หัวหิน

In [ ]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]   #2.   ใส่ rows ที่ต้องการ เอาแถวไหน = true ไม่เอา =false

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
5,6,25/1/2020,NaN,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [ ]:
eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร'  #สร้าง list ของ logical expression แจ่ละแถว = กทม ป่าว ช่=ทรู ไม่ช่=ฟล้อว

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: province_of_onset, dtype: bool

In [ ]:
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร']  #เราเอา 2 บรรทัดบนมาบวกกัน

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
5,6,25/1/2020,NaN,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
6,7,26/1/2020,NaN,หญิง,57.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

## HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data

         sex   age province_of_onset
0       หญิง  61.0     กรุงเทพมหานคร
1       หญิง  74.0     กรุงเทพมหานคร
2       หญิง  73.0            นครปฐม
3        ชาย  68.0     กรุงเทพมหานคร
4       หญิง  66.0     กรุงเทพมหานคร
...      ...   ...               ...
839766   ชาย  52.0         กาญจนบุรี
839767   ชาย  34.0         กาญจนบุรี
839768   ชาย  31.0         กาญจนบุรี
839769   ชาย  83.0         กาญจนบุรี
839770   ชาย  47.0         กาญจนบุรี

[839771 rows x 3 columns]

In [ ]:
female = this_data[this_data['sex']=='หญิง']
female['age']

0         61.0
1         74.0
2         73.0
4         66.0
5         33.0
          ...
839737    57.0
839738    50.0
839739    37.0
839740    24.0
839741    26.0
Name: age, Length: 399881, dtype: object

In [ ]:
female_age_numeric = pd.to_numeric(female['age'], errors='coerce').dropna()

sum_age = 0
N_age = 0
for a in female_age_numeric:
    if a > 0:
        sum_age += a # sum = sum + a
        N_age += 1

if N_age > 0:
    print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง {sum_age/N_age}')
else:
    print('ไม่พบข้อมูลอายุที่เป็นบวกสำหรับผู้ป่วยหญิง')

อายุเฉลี่ย ของ ผู้ป่วยหญิง 36.16090881617699

In [ ]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']

female_KK_age_numeric = pd.to_numeric(female_KK['age'], errors='coerce').dropna()

sum_age_KK = 0
N_age_KK = 0
for a in female_KK_age_numeric:

    if a > 0:
        sum_age_KK += a
        N_age_KK += 1

if N_age_KK > 0:
    print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum_age_KK/N_age_KK}')
else:
    print('ไม่พบข้อมูลอายุที่เป็นบวกสำหรับผู้ป่วยหญิงในจังหวัดขอนแก่น')

อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 34.59362745098039

In [ ]:
male = this_data[this_data['sex']=='ชาย']
male['age']

3         68.0
8         63.0
10        33.0
11        61.0
12         6.0
          ...
839766    52.0
839767    34.0
839768    31.0
839769    83.0
839770    47.0
Name: age, Length: 384994, dtype: object

In [ ]:
male_age_numeric = pd.to_numeric(male['age'], errors='coerce').dropna()

sum_age = 0
N_age = 0
for a in male_age_numeric:
    if a > 0:
        sum_age += a
        N_age += 1

if N_age > 0:
    print(f'อายุเฉลี่ย ของ ผู้ป่วยชาย {sum_age/N_age}')
else:
    print('ไม่พบข้อมูลอายุที่เป็นบวกสำหรับผู้ป่วยชาย')

อายุเฉลี่ย ของ ผู้ป่วยชาย 34.962927021309376

3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

In [ ]:
male_KK = male[male['province_of_onset']=='ขอนแก่น']

male_KK_age_numeric = pd.to_numeric(male_KK['age'], errors='coerce').dropna()

sum_age_KK = 0
N_age_KK = 0
for a in male_KK_age_numeric:

    if a > 0:
        sum_age_KK += a
        N_age_KK += 1

if N_age_KK > 0:
    print(f'อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น {sum_age_KK/N_age_KK}')
else:
    print('ไม่พบข้อมูลอายุที่เป็นบวกสำหรับผู้ป่วยชายในจังหวัดขอนแก่น')

อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น 34.057632398753896

ข้อ 3

In [ ]:
foreign_travelers = data_covid[data_covid['risk'] == 'คนต่างชาติเดินทางมาจากต่างประเทศ']
num_foreign_travelers = len(foreign_travelers)
print(f"จำนวนผู้ป่วยที่เป็น \"คนต่างชาติเดินทางมาจากต่างประเทศ\": {num_foreign_travelers}")

จำนวนผู้ป่วยที่เป็น "คนต่างชาติเดินทางมาจากต่างประเทศ": 225

##การจัดการ Missing Value

การจัดการ Missing Value

- ลบ record ที่เป็น missing
- แทนที่ ค่า missing ด้วยค่าที่เหมาะสม mean, default, category-unknown
- ใช้ ค่าจาก columns อื่นๆ ช่วยประมาณค่า ค่าใน column ที่หายไป (regression, deep learning, etc.)

### ลบ record (dropna)

missing = ```None``` ```NA```(not autorized) ```NaN``` (not a number)

In [ ]:
this_data.shape #(12423, 3)

(839771, 3)

In [ ]:
print(data_covid.shape)
print(data_covid.dropna().shape)

(839771, 11)
(599988, 11)

In [ ]:
this_data.dropna().shape

(674906, 3)

In [ ]:
this_data.dropna()

         sex   age province_of_onset
0       หญิง  61.0     กรุงเทพมหานคร
1       หญิง  74.0     กรุงเทพมหานคร
2       หญิง  73.0            นครปฐม
3        ชาย  68.0     กรุงเทพมหานคร
4       หญิง  66.0     กรุงเทพมหานคร
...      ...   ...               ...
839766   ชาย  52.0         กาญจนบุรี
839767   ชาย  34.0         กาญจนบุรี
839768   ชาย  31.0         กาญจนบุรี
839769   ชาย  83.0         กาญจนบุรี
839770   ชาย  47.0         กาญจนบุรี

[674906 rows x 3 columns]

In [ ]:
this_data.dropna()
print(this_data.shape)

(839771, 3)

In [ ]:
this_data.dropna(inplace=True)

/tmp/ipykernel_662/3935554116.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

In [ ]:
this_data.dropna(inplace=True)
print(this_data.shape)

(674906, 3)

/tmp/ipykernel_662/2129530393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

### แทน missing ด้วยค่าที่เหมาะสม (```fillna```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [ ]:
print(f'จำนวน record ก่อน drop missing ใน province {this_data.shape[0]}')
print(f'จำนวน record หลัง drop missing ใน province {this_data.dropna(subset=["province_of_onset"]).shape[0]}')

จำนวน record ก่อน drop missing ใน province 839771
จำนวน record หลัง drop missing ใน province 740737

In [ ]:
this_data_updated = this_data.fillna(value={'sex':'ไม่รู้', 'age':-1, 'province_of_onset':'ไม่รู้'})
this_data_updated.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [ ]:
this_data_updated[this_data_updated['sex']=='ไม่รู้']

           sex   age province_of_onset
4397    ไม่รู้    -1         สมุทรสาคร
4398    ไม่รู้    -1         สมุทรสาคร
4399    ไม่รู้    -1         สมุทรสาคร
4400    ไม่รู้    -1         สมุทรสาคร
4401    ไม่รู้    -1         สมุทรสาคร
...        ...   ...               ...
838332  ไม่รู้   3.0     กรุงเทพมหานคร
839174  ไม่รู้  47.0     กรุงเทพมหานคร
839304  ไม่รู้    -1            ไม่รู้
839396  ไม่รู้    -1        นครราชสีมา
839397  ไม่รู้    -1        นครราชสีมา

[54895 rows x 3 columns]

In [ ]:
this_data_updated['province_of_onset']=='ไม่รู้'

0         False
1         False
2         False
3         False
4         False
          ...
839766    False
839767    False
839768    False
839769    False
839770    False
Name: province_of_onset, Length: 839771, dtype: bool

In [ ]:
data_covid[this_data_updated['province_of_onset']=='ไม่รู้']

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
415,416,22/3/2020,22/3/2020,ชาย,29.0,ปี,Thailand,กรุงเทพมหานคร,สนามมวย,NaN,NaN
530,531,22/3/2020,20/3/2020,ชาย,37.0,ปี,Thailand,กรุงเทพมหานคร,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,NaN,NaN
556,557,22/3/2020,21/3/2020,หญิง,6.0,ปี,Thailand,กรุงเทพมหานคร,สนามมวย,NaN,NaN
577,578,22/3/2020,20/3/2020,ชาย,NaN,NaN,Thailand,กรุงเทพมหานคร,สนามมวย,NaN,NaN
589,590,22/3/2020,21/3/2020,ชาย,NaN,NaN,Thailand,กรุงเทพมหานคร,อยู่ระหว่างการสอบสวน,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
838196,838197,12/8/2021,11/8/2021,NaN,36.0,ปี,NaN,กรุงเทพมหานคร,ระบุไม่ได้,NaN,NaN
838371,838372,12/8/2021,11/8/2021,ชาย,28.0,ปี,Cambodian,กรุงเทพมหานคร,อื่นๆ,NaN,NaN
838395,838396,12/8/2021,11/8/2021,ชาย,45.0,ปี,Cambodian,กรุงเทพมหานคร,ระบุไม่ได้,NaN,NaN
839144,839145,12/8/2021,11/8/2021,ชาย,76.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,NaN,NaN
839304,839305,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,กรุงเทพมหานคร,ระบุไม่ได้,NaN,NaN

In [ ]:
this_data_updated_2 = this_data.fillna(value={'province_of_onset':'ไม่รู้'})

In [ ]:
this_data_updated_2[this_data_updated['sex']=='ไม่รู้']

        sex   age province_of_onset
4397    NaN   NaN         สมุทรสาคร
4398    NaN   NaN         สมุทรสาคร
4399    NaN   NaN         สมุทรสาคร
4400    NaN   NaN         สมุทรสาคร
4401    NaN   NaN         สมุทรสาคร
...     ...   ...               ...
838332  NaN   3.0     กรุงเทพมหานคร
839174  NaN  47.0     กรุงเทพมหานคร
839304  NaN   NaN            ไม่รู้
839396  NaN   NaN        นครราชสีมา
839397  NaN   NaN        นครราชสีมา

[54895 rows x 3 columns]

### การวนลูป record ในตาราง  (```.iterrows```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
for each_row in this_data.iterrows():
    # print(each_row)
    # print(each_row[1])
    if (each_row[1]['age'] == 20) and (each_row[1]['province_of_onset'] == 'บุรีรัมย์'):
        print(each_row)

(32903, sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 32903, dtype: object)
(37955, sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 37955, dtype: object)
(37956, sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 37956, dtype: object)
(342622, sex                        NaN
age                       20.0
province_of_onset    บุรีรัมย์
Name: 342622, dtype: object)
(349692, sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 349692, dtype: object)
(349748, sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 349748, dtype: object)
(349759, sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 349759, dtype: object)
(367664, sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 367664, dtype: object)
(368577, sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 368577, dtype: object)
(388137, sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 388137, dtype: object)
(388138, sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 388138, dtype: object)
(648214, sex                        NaN
age                       20.0
province_of_onset    บุรีรัมย์
Name: 648214, dtype: object)
(654407, sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 654407, dtype: object)
(669860, sex                        NaN
age                       20.0
province_of_onset    บุรีรัมย์
Name: 669860, dtype: object)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```)

In [ ]:
for each_row in range(this_data.shape[0]): # each_row วนตามแถว this_data.shape[0] ต้องดูตั้งแต่ row ที่ 0
    if (this_data.iloc[each_row,1] == 20) and (this_data.iloc[each_row,2] == 'บุรีรัมย์'):  #each_row คือ ตัวเลข (ตรง 1 คือหลักที่ 2 เป็น 1 งงมั้ยกูงง)
        print(each_row)
        print(this_data.iloc[each_row,:])

32903
sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 32903, dtype: object
37955
sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 37955, dtype: object
37956
sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 37956, dtype: object
342622
sex                        NaN
age                       20.0
province_of_onset    บุรีรัมย์
Name: 342622, dtype: object
349692
sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 349692, dtype: object
349748
sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 349748, dtype: object
349759
sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 349759, dtype: object
367664
sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 367664, dtype: object
368577
sex                        ชาย
age                       20.0
province_of_onset    บุรีรัมย์
Name: 368577, dtype: object
388137
sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 388137, dtype: object
388138
sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 388138, dtype: object
648214
sex                        NaN
age                       20.0
province_of_onset    บุรีรัมย์
Name: 648214, dtype: object
654407
sex                       หญิง
age                       20.0
province_of_onset    บุรีรัมย์
Name: 654407, dtype: object
669860
sex                        NaN
age                       20.0
province_of_onset    บุรีรัมย์
Name: 669860, dtype: object

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data.shape

(839771, 3)

In [ ]:
this_data.dropna().shape

(674906, 3)

In [ ]:
this_data.dropna(subset=['age']).shape

(763606, 3)

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [ ]:
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
124,125,6/3/2021,5/3/2021,หญิง,55.0,ปี,Thailand,ปทุมธานี,Cluster ตลาดพรพัฒน์,ปทุมธานี,ธัญบุรี
6885,6886,1/1/2021,31/12/2020,หญิง,40.0,ปี,Thailand,กรุงเทพมหานคร,Cluster สมุทรสาคร,ปทุมธานี,คลองหลวง
6886,6887,1/1/2021,31/12/2020,หญิง,21.0,ปี,Thailand,ปทุมธานี,Cluster ระยอง,ปทุมธานี,คลองหลวง
6887,6888,1/1/2021,31/12/2020,หญิง,20.0,ปี,Thailand,นครปฐม,สถานบันเทิง,นครปฐม,สามพราน
6888,6889,1/1/2021,31/12/2020,หญิง,47.0,ปี,Thailand,สมุทรสาคร,Cluster สมุทรสาคร,นครปฐม,สามพราน

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [ ]:
data_covid.describe()

                No.
count  839771.00000
mean   419886.00000
std    242421.15079
min         1.00000
25%    209943.50000
50%    419886.00000
75%    629828.50000
max    839771.00000

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [117]:
data_covid[data_covid['sex']=='ชาย']['age'].mean()

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [ ]:
male_age = data_covid[data_covid['sex']=='ชาย']['age']
male_age_numeric = pd.to_numeric(male_age, errors='coerce').dropna()
print(f"อายุเฉลี่ยของผู้ป่วยชาย: {male_age_numeric.mean()}")

อายุเฉลี่ยของผู้ป่วยชาย: 34.96292702130938

### ```.isnull()```

In [ ]:
data_covid.isnull()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,False,False,True,False,False,False,False,False,False,False,True
1,False,False,True,False,False,False,False,False,False,False,True
2,False,False,True,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,True
4,False,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
839766,False,False,False,False,False,False,True,False,False,False,True
839767,False,False,False,False,False,False,False,False,False,False,True
839768,False,False,False,False,False,False,False,False,False,False,True
839769,False,False,False,False,False,False,False,False,False,False,True
839770,False,False,False,False,False,False,False,False,False,False,True

# next
*   .describe
*   .mean
*   HW วนลูป missing .isnull
*   ต่อตารางแกน X แกน y
*   .groupby
*   save table